# Generated by Django 5.1.2 on 2024-11-04 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
