# Generated by Django 5.1.3 on 2024-11-10 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0004_discount_filter_remove_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSizeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appproject.discount')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='appproject.productsize')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductDiscount',
        ),
    ]
