# Generated by Django 5.1.3 on 2024-11-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0005_productsizediscount_delete_productdiscount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
